table Dim_Calendario
	lineageTag: 94639e69-d220-4c13-8b8b-4c79ff6d39ec

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 35ab9115-c451-4e51-b767-19be7107b5a1
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: e7226bf3-94c8-423e-b312-5551ad75bd70
			defaultHierarchy: LocalDateTable_19f068e2-f6b7-4bcf-881b-43327d4363c8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: e50e44f3-607e-4c3f-8d86-c39a4ed4ce51
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: d8b8223a-303d-4a1b-9b71-ee1bde461450
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 9466f5c5-ba74-4649-a441-89adf55d31d9
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 6996cdd1-a827-4b8b-b5e2-81e82f3531a6
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 42def954-9dfa-4767-833b-9f01fd24ce53
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\jesus\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

